services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file: .env
    volumes:
      - wp-db:/var/lib/mysql  # ← named volume

    networks:
      - inception
    restart: on-failure


  wordpress:
    # WordPress → MariaDB via mariadb:3306
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file: .env
    volumes:
      - wp-files:/var/www/html  # ← named volume

    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb


  nginx:
    # NGINX → WordPress via wordpress:9000
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/html  # ← same volume, shared with wordpress

    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress



# driver: local          → use Docker's built-in local storage driver
# type: none             → no special filesystem type, use the host's existing filesystem
# o: bind                → mount option "bind" — map to an exact host path
# device: /home/...      → which host path to bind to
volumes:
  wp-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tkremnov/data/db  # /home/${USER}/data/db

  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tkremnov/data/wordpress


networks:
  inception:
    driver: bridge

# Browser → NGINX (443) → WordPress+php-fpm (9000) → MariaDB (3306)
