services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - wp-db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    # WordPress → MariaDB via mariadb:3306
    networks:
      - inception

  nginx:
    # NGINX → WordPress via wordpress:9000
    networks:
      - inception

volumes:
  wp-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

networks:
  inception:
    driver: bridge